# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js image for the build environment
FROM node:16-alpine AS builder

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json /app/

# Install dependencies
RUN npm install

# Copy the rest of the source code
COPY . /app

# Build the application
RUN npm run build

# Set file permissions (if necessary)
RUN node scripts/set-permissions.js

# Use a separate image for the production environment
FROM node:16-alpine AS production

# Set the working directory inside the container
WORKDIR /app

# Copy the build output and package files from the builder stage
COPY --from=builder /app/build /app/build
COPY --from=builder /app/package.json /app/package.json
COPY --from=builder /app/package-lock.json /app/package-lock.json

# Install production dependencies only
RUN npm install --omit=dev

# Run the application
ENTRYPOINT ["node", "build/index.js"]
